#!/usr/bin/env python3

from http.server import BaseHTTPRequestHandler, HTTPServer
import os


class RequestHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()

        content_length = int(self.headers["Content-Length"])
        post_data = self.rfile.read(content_length)
        print(post_data.decode("utf-8"), flush=True)

        self.wfile.write(b"OK")

    def log_message(self, format: str, *args) -> None:
        pass


def main():
    hostname = os.getenv("INCOMING_HOSTNAME") if os.getenv("INCOMING_HOSTNAME") else "localhost"
    port = int(os.getenv("INCOMING_PORT")) if os.getenv("INCOMING_PORT") else 9493

    server = HTTPServer((hostname, port), RequestHandler)
    server.serve_forever()

if __name__ == "__main__":
    main()
